### ISSUE TITLE
Customizable output file

### ISSUE THREAD

**Issue by vincevargadev** [dartsidedev/build_pubspec#2]

**Comment by vincevargadev** [comment]
Add in your `build.yaml`:

```yaml
targets:
  $default:
    builders:
      build_pubspec:
        options:
          destination_file: 'lib/details.dart'
```
